### PR TITLE
Changes to allow JSON mapping of inherited class properties

### PR DESCRIPTION
**Pull request by seanmccleary**
PR for issue #90 (and also #96)

I hope the implementation is OK.  There's no response on the issue so I didn't have much guidance. I chose to use an annotation so as not to break backward compatibility with the behavior.   If this should be done in some other way, let me know and I'm happy to change it.

### CODE REVIEW

**Comment by seanmccleary** [comment]
I signed it

**Comment by kevmoo** [comment]
CC @mkustermann

**Comment by mkustermann** [comment]
LGTM

**Comment by mkustermann** [comment]
@seanmccleary Thank you for your contribution. The change has been merged and a new version was published.

**Pull request merged**
