### PR TITLE
Add errors to RpcError

### PR DESCRIPTION
**Pull request by enyo**
As discussed in #63 

I added tests for all the new functionality, and formatted my code with `dartfmt`. I did only commit the `dartfmt` changes in my code changes though (the original code was not formatted with the tool).

### CODE REVIEW

**Comment by enyo** [comment]
@wibling @sgjesse is there something you want me to change?

**Comment by wibling** [comment]
Sorry for the delayed review. I had missed the request.
It looks good and thanks for adding tests as well.

**Comment by enyo** [comment]
No problem. Thanks for reviewing & merging.

**Comment by enyo** [comment]
Would you mind publishing it to `pub`?

**Comment by wibling** [comment]
Sorry about that. It should be published now.

/gustav

**Pull request merged**
