### PR TITLE
misc: support latest pkg:gcloud, other cleanup

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
How close are we to being able to be stable here?

**Comment by jcollins-g** [comment]
We could theoretically call this stable; I was hoping to get more user feedback but maybe that won't happen until we do.

**Comment by kevmoo** [comment]
> Don't know about the codereview.settings effects, but seems reasonable.

Oldschool before we did reviews on github

**Comment by kevmoo** [comment]
@jcollins-g – bumped this PR to make it the release. Cool?

**Comment by kevmoo** [comment]
Perfect!

**Pull request merged**
