### PR TITLE
decode url query and path

### LINKED ISSUE #64: Decode URL query & path
When using the generated client libraries for RPC, the path and query components are encoded automatically (eg: `%20`). They are not, however decoded on the server side, so I need to decode them in the `ApiMethod` manually.

I think that this should be done behind the scenes.

### PR DESCRIPTION
**Pull request by Kleak**
should fix #64

### CODE REVIEW

**Comment by kevmoo** [comment]
@Kleak could you add a test for this as well?

**Comment by Kleak** [comment]
@kevmoo yes i will do that ASAP

**Comment by Kleak** [comment]
Is there normal that when i run pub run test i have this message :
```unittest-suite-wait-for-done
No tests ran.```

**Comment by mkustermann** [comment]
Sorry this PR has been hanging around for so long. I've just merged it (and resolved a few minor conflicts).

**Pull request merged**
