### PR TITLE
issue 45: updated shelf_rpc dependency to any

### PR DESCRIPTION
**Pull request by iamcharliegoddard**
updating to any resolves the issue.

### CODE REVIEW

**Comment by iamcharliegoddard** [comment]
I signed it!

**Comment by kevmoo** [comment]
Updating any dependency to `any` is dangerous. What is the max release that is compatible? We can be explicit.

**Comment by iamcharliegoddard** [comment]
agreed, however, for this particular case, where a dependency has a dependency of a dependency to itself, it should be fine due to the [inception](http://www.imdb.com/title/tt1375666/) like circular dependency rpc `/example` has for `shelf_rpc`. If the dependency is bumped to `rpc 0.6.0` when `rpc 0.6.0` is release [this issue](https://github.com/dart-lang/rpc/issues/45) reoccurs. 

thoughts?

**Comment by iamcharliegoddard** [comment]
@wibling, this works, and it's a reasonable solution to avoid the same issue in the future.

**Comment by wibling** [comment]
I don't think using any is the right solution. Off hand I don't know of a good solution, except perhaps moving the RPC shelf example to the shelf_rpc package.
I will update the shelf_rpc package's dependency to the latest version of RPC which should also fix the issue and keep the examples working.

**Comment by iamcharliegoddard** [comment]
Could a separate `pubspec.yaml` file added in `example/` with a `shelf_rpc` dependency of `^0.0.3` work? Then remove the `shelf*` dependencies from the root `pubspec.yaml` file.

**Comment by zoechi** [comment]
subproject in `example` doesn't work well, `pub get` creates a `packages` symlink in any subdirectory pointing to the main projects `packages` directory. If you want to make a subdirectory its own package use a non-default subfolder name (none of `bin`, `doc`, `example`, `test`, `tool`, `web`)

**Pull request closed without merging**
