### PR TITLE
MediaMessage. List inheritance.

### PR DESCRIPTION
**Pull request by tristancaron**
Support of Blob files (download).

If you found something bad or missing, let me know :smiley:

### CODE REVIEW

**Comment by FaisalAbid** [comment]
Looks good to me! Great work @tristancaron 

@wibling what do you think?

**Comment by FaisalAbid** [comment]
@tristancaron can you squash the two commits with the same message into one please?

**Comment by tristancaron** [comment]
Well, almost... Now we have a new message... I don't know how to proceed... :confused:

**Comment by FaisalAbid** [comment]
you can do the following and it should work

git rebase -i HEAD~3

then squash the last commit "merge remote-tracking" into the previous one.

Then when it asks you to update the commit message, you can remove the "merge remote-tracking" message.

Finally git push -f and all should be good

**Comment by tristancaron** [comment]
I've tried, but the commit "merge remote-tracking" doesn't appear in the list... Maybe I should make a new pull request, what do you think?

Also, I think to implement the upload part this week. I've saw that we don't have a real form body parser. The package `http_server` has a good one, I think use it, no problem with it?

**Pull request closed without merging**
