### PR TITLE
Update README.md to communicate that this is not being maintained

### PR DESCRIPTION
**Pull request by mit-mit**

### CODE REVIEW

**Comment by supermuka** [comment]
What a pity! This package is really good for implementing RESTful web APIs! As an alternative to this package, dart-grpc is already working for web (browser)?

**Comment by jcollins-g** [comment]
@supermuka I thought that we'd be porting dart-lang/dart-services to grpc, however grpc/grpc-dart#43 is still open.  @mit-mit is this functionality planned to land soon?

**Comment by mit-mit** [comment]
> however grpc/grpc-dart#43 is still open. @mit-mit is this functionality planned to land soon?

I hope see, see https://github.com/grpc/grpc-dart/pull/109#issuecomment-448236451

**Comment by kevmoo** [comment]
Are we going to publish a 0.6.1 w/ the updated readme? Or should we just archive this package now.

**Comment by jcollins-g** [comment]
I think the package has already been marked as discontinued on pub.  We can publish a 0.6.1 with the readme update too if that's helpful?

**Comment by kevmoo** [comment]
> I think the package has already been marked as discontinued on pub. We can publish a 0.6.1 with the readme update too if that's helpful?

It is. I'll move this to archive. Glad we're tracking the migration to grpc somewhere else.

**Pull request merged**
